resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
  - name: govuk-aws-pr
    type: pull-request
    check_every: 1m
    source:
      repository: alphagov/govuk-aws
      access_token: ((concourse_ci_access_token))
      disable_forks: true

jobs:
  - name: build-govuk-aws-pr
    public: true
    serial: true
    plan:
      - get: govuk-aws-pr
        trigger: true
        version: every
      - put: govuk-aws-pr
        params:
          status: pending
          path: govuk-aws-pr
      - task: check-terraform-docs-updatedness
        timeout: 15m
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: homebrew/brew
              tag: 2.2.1
          inputs:
            - name: govuk-aws-pr
              path: repo
          params:
            HOMEBREW_NO_AUTO_UPDATE: 1
            HOMEBREW_DEVELOPER: 1
          run:
            path: bash
            dir: repo
            args:
            - -c
            - |
              # It's not a Concourse pipeline without some sed (until this gets into a Homebrew release)...
              sed -i 's/azpl_job|docker|kubepods/azpl_job|docker|garden|kubepods/g' $(brew --repo)/Library/Homebrew/brew.sh
              brew update
              brew install terraform-docs

              echo "Checking the updatedness of README files..."
              ./tools/update-docs.sh

              if [[ ! $(git diff --exit-code) ]]; then
                echo "The documentation isn't up to date. You should run ./tools/update-docs.sh and commit the results."
                exit 1
              fi
    on_success:
      put: govuk-aws-pr
      params:
        path: govuk-aws-pr
        status: success
    on_failure:
      put: govuk-aws-pr
      params:
        path: govuk-aws-pr
        status: failure

